CREATE TABLE HERTZ_UTS.RENTING_HISTORY (
  ID int NOT NULL AUTO_INCREMENT,
  CAR_ID int NOT NULL,
  CUSTOMER_DETAILS_ID int NOT NULL,
  USER_EMAIL varchar(255) NOT NULL,
  RENT_DATE date NOT NULL,
  RETURN_DATE date NOT NULL,
  BOND_AMOUNT int NOT NULL,
  PRIMARY KEY (ID)
);
